### ISSUE TITLE
Wanna cooperate?

### ISSUE THREAD

**Issue by BlackPhrase** [kennyrkun/Server-Client#1]
Hello
Looks like you're writing a client-server game
And I have some WIP client-server game engine
https://github.com/BlackPhrase/308
What about using that engine to run your game?
By looking at your projects it pretty much looks like you need an engine
It can't do much atm but I think it has a good potential with such architecture (it's literally a V-engine with client and server sides split into their own modules)

**Comment by kennyrkun** [comment]
I think I might.

Add me on Discord, communibb#1337

**Comment by BlackPhrase** [comment]
Sorry, I'm not using it

**Comment by kennyrkun** [comment]
Well, from what I've seen in the 308 repository, it doesn't seem like it's in a functional state. I'm unable to test it now, but there are many commented out methods which look like they'd be important. 

Also, it seems to lack documentation. I might just be looking in the wrong place, but I can't find anything that says what these methods and classes do. The engine looks to be structured much the same way the Source Engine is, and I'm not quite sure if that's the way I want to go.

Can you show me how your engine might work for me?

**Comment by BlackPhrase** [comment]
Well, as I said, it's in a very WIP state
Last time I tried it was buildable
You need to update the submodules and put the glfw3 in the "external/" folder
That's for the master branch
The current state of the dev branch is definitely broken

**Comment by kennyrkun** [comment]
Does the engine handle graphics, or no? If so, what exactly does it do?
Does it doe event handling as well? 

I have my own solutions to both of these, but an all-in-one solution is of course ideal.

I was thinking of using Valve's networking sockets library. What advantages does your engine have over that one?

**Comment by BlackPhrase** [comment]
At this point, client side is only able to open a glfw window
Some event handling for window and input is also on glfw responsibilities right now

I'm not planning to directly use some external APIs, they all will be hidden by internal interfaces, so if you want to use (C)SFML - go ahead, I'll provide a set of internal interfaces for it later

It structured differently from the Source Engine
The launcher loads the engine core module (dll), initializes it and runs the engine
The engine core loads network, physics, (script), client and server side modules (all dlls)
The server-side module will load the game dll (I'm also planning to let it load Lua script instead of dll)
The client-side module will load the input, sound, render modules (and probably client dll) or initialize them internally in case their support is implemented by some SFML/SDL-like library

It doesn't have any own networking support atm, so go ahead

**Comment by kennyrkun** [comment]
Does the server handle the game logic?

This game uses a dedicated server, to which clients can connect and disconnect whenever they choose. The server is meant to run for days or weeks at a time without stopping. Does 308 work like that or more like Source, where the client connects to a local server?

**Comment by kennyrkun** [comment]
ok, cool.

Yea, I'll try to use your engine when I can. Right now I need to cleanup and make this functional. I have a bunch of uncommitted changes.
